### ISSUE TITLE
Crash at repl (Node.js)

### ISSUE THREAD

**Issue by hlandau** [udem-dlteam/ribbit#4]
Using head.
```
$ guile -s rsc.scm -t js -l min repl-min.scm
$ node repl-min.scm.js
> 42
42
> (define x 42)
0
> x
42
> '(a b)
(a b)
> `(a b c (d e))
#f
> /home/hugo/Downloads/ribbit-main/src/repl-min.scm.js:177
    let o = pc[1];
              ^

TypeError: Cannot read property '1' of undefined
    at run (/home/hugo/Downloads/ribbit-main/src/repl-min.scm.js:177:15)
    at Object.<anonymous> (/home/hugo/Downloads/ribbit-main/src/repl-min.scm.js:235:13)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by feeley** [comment]
The backquote is not parsed by Ribbit (the `quasiquote` form is not yet implemented).  So the backquote is seen as a single character variable and undefined variables have a default value of `#f`.  Then the `(a b c (d e))` is read and this will call the undefined procedure `d` so it is equivalent to `(#f #f)` and this crashes the RVM.  Ribbit does almost no error detection in order to fit everything in 4K.  Future versions are planned that trade the footprint for more features.
